[workspace]
resolver = "3"
members = ["zinq", "errorx", "errorx-macros", "extendx", "macrox", "reflectx", "reflectx-macros"]
default-members = ["zinq", "errorx", "errorx-macros", "extendx", "macrox", "reflectx", "reflectx-macros"]

[workspace.package]
version = "0.0.0"
edition = "2024"
license = "MIT"
readme = "README.md"
description = "a family of tools that facilitate schema based use cases, including querying, validation, and more."
documentation = "https://www.github.com/aacebo/zinq"
homepage = "https://www.github.com/aacebo/zinq"
repository = "https://www.github.com/aacebo/zinq"

[workspace.dependencies]
reflectx = { path = "./reflectx", version = "0.0.0" }
reflectx-macros = { path = "./reflectx-macros", version = "0.0.0" }
macrox = { path = "./macrox", version = "*" }
extendx = { path = "./extendx", version = "0.0.0" }
errorx = { path = "./errorx", version = "0.0.0" }
errorx-macros = { path = "./errorx-macros", version = "0.0.0" }

serde = { version = "1" }
syn = { version = "2" }
quote = { version = "1" }
proc-macro2 = { version = "1" }