[package]
name = "zinq"
description = "a relational schema framework."
readme = "README.md"
version.workspace = true
edition.workspace = true
license.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
macros = ["reflectx/macros", "errorx/macros"]
reflect = ["dep:reflectx"]
error = ["dep:errorx"]
extend = ["dep:extendx"]
parse = ["dep:macrox"]
serde = ["dep:serde", "serde/derive", "reflectx/serde", "errorx/serde"]

[dependencies]
reflectx = { workspace = true, optional = true }
extendx = { workspace = true, optional = true }
errorx = { workspace = true, optional = true }
macrox = { workspace = true, optional = true }
serde = { workspace = true, optional = true }