[package]
name = "zinq"
description = "a relational schema framework."
readme = "README.md"
version.workspace = true
edition.workspace = true
license.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
macros = ["zinq-reflect/macros", "zinq-error/macros"]
error = ["dep:zinq-error"]
serde = ["dep:serde", "serde/derive", "zinq-reflect/serde", "zinq-error/serde"]

[dependencies]
zinq-reflect = { workspace = true }
zinq-error = { workspace = true, optional = true }
serde = { workspace = true, optional = true }